# Site settings
title: Kabu Creative
email: "info@kabucreative.com"
url: "http://www.kabucreative.com"

# Build settings
timezone: Australia/Melbourne
highlighter: pygments

sass:
    sass_dir: /assets/css/_sass
    style: :compressed

exclude: [vendor]

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
