# Site settings
title: Kabu Creative
email: info@kabucreative.com.au
url: "http://www.kabucreative.com.au"

# Build settings
timezone: Australia/Melbourne
highlighter: pygments

sass:
    sass_dir: /assets/css/_sass
    style: :compressed

exclude: [vendor]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

